import re

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

import board_store as bs
import canvas_sync
import card_store as cs
import edge_store as es
import search_logic
from models import (
    AddSession,
    CreateBoard,
    CreateCard,
    CreateColumn,
    CreateEdge,
    EnsureProjectBoard,
    MoveCard,
    UpdateBoard,
    UpdateCard,
    UpdateColumn,
)

# IDs are 12-char hex strings generated by _uid()
_ID_RE = re.compile(r"^[0-9a-f]{12}$")

app = FastAPI(title="Agent Board")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:5174",
        "http://localhost:5175",
        "http://localhost:5176",
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)


def _validate_id(value: str, name: str = "id") -> str:
    if not _ID_RE.match(value):
        raise HTTPException(400, f"Invalid {name}")
    return value


def _board_or_404(board_id: str):
    _validate_id(board_id, "board_id")
    board = bs.get_board(board_id)
    if not board:
        raise HTTPException(404, "Board not found")
    return board


def _sync_board_if_enabled(board_id: str) -> None:
    canvas_sync.sync_if_enabled(board_id)


class ImportCard(BaseModel):
    external_id: str = ""
    title: str
    body: str = ""
    column: str
    parent_external_id: str | None = None
    priority: str = "medium"
    labels: list[str] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)


class ImportBoard(BaseModel):
    name: str
    description: str = ""
    columns: list[str]
    cards: list[ImportCard] = Field(default_factory=list)


class CanvasSyncEnable(BaseModel):
    canvas_api_url: str | None = None


# --- Boards ---

@app.get("/api/boards")
def api_list_boards():
    return bs.list_boards()


@app.post("/api/boards", status_code=201)
def api_create_board(body: CreateBoard):
    return bs.create_board(body.name, body.description, body.columns)


@app.get("/api/boards/{board_id}")
def api_get_board(board_id: str):
    return _board_or_404(board_id)


@app.patch("/api/boards/{board_id}")
def api_update_board(board_id: str, body: UpdateBoard):
    board = bs.update_board(board_id, **body.model_dump(exclude_none=True))
    if not board:
        raise HTTPException(404, "Board not found")
    _sync_board_if_enabled(board_id)
    return board


@app.delete("/api/boards/{board_id}")
def api_delete_board(board_id: str):
    _board_or_404(board_id)
    canvas_sync.disable_sync(board_id)
    if not bs.delete_board(board_id):
        raise HTTPException(404, "Board not found")
    return {"ok": True}


@app.post("/api/projects/ensure-board")
def api_ensure_project_board(body: EnsureProjectBoard):
    try:
        return bs.ensure_project_board(body.remote_url, body.name, body.description, body.columns)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/import/board", status_code=201)
def api_import_board(body: ImportBoard):
    if not body.columns:
        raise HTTPException(400, "columns must not be empty")
    board = bs.create_board(body.name, body.description, body.columns)
    columns = {col.name: col.id for col in board.columns}
    created_by_external_id: dict[str, str] = {}
    pending = list(body.cards)
    while pending:
        remaining: list[ImportCard] = []
        created_any = False
        for card in pending:
            column_id = columns.get(card.column)
            if not column_id:
                raise HTTPException(400, f"unknown column: {card.column}")
            parent_id = None
            if card.parent_external_id:
                parent_id = created_by_external_id.get(card.parent_external_id)
                if not parent_id:
                    remaining.append(card)
                    continue
            created = cs.create_card(board.id, CreateCard(
                external_id=card.external_id,
                title=card.title,
                body=card.body,
                column_id=column_id,
                parent_id=parent_id,
                priority=card.priority,
                labels=card.labels,
                metadata=card.metadata,
            ))
            if not created:
                raise HTTPException(400, f"failed to create card: {card.title}")
            if card.external_id:
                created_by_external_id[card.external_id] = created.id
            created_any = True
        if remaining and not created_any:
            missing = sorted({c.parent_external_id for c in remaining if c.parent_external_id})
            raise HTTPException(400, f"unknown parent_external_id values: {missing}")
        pending = remaining
    return board


@app.get("/api/boards/{board_id}/canvas-sync")
def api_get_canvas_sync(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.get_sync_status(board_id)


@app.post("/api/boards/{board_id}/canvas-sync/enable")
def api_enable_canvas_sync(board_id: str, body: CanvasSyncEnable | None = None):
    _board_or_404(board_id)
    try:
        return canvas_sync.enable_sync(board_id, body.canvas_api_url if body else None)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/canvas-sync/disable")
def api_disable_canvas_sync(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.disable_sync(board_id)


@app.post("/api/boards/{board_id}/canvas-sync/sync")
def api_sync_canvas(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.sync_board(board_id)


# --- Columns ---

@app.post("/api/boards/{board_id}/columns", status_code=201)
def api_add_column(board_id: str, body: CreateColumn):
    _board_or_404(board_id)
    col = bs.add_column(board_id, body.name, body.position)
    if not col:
        raise HTTPException(400, "Failed to add column")
    _sync_board_if_enabled(board_id)
    return col


@app.patch("/api/boards/{board_id}/columns/{column_id}")
def api_update_column(board_id: str, column_id: str, body: UpdateColumn):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    col = bs.update_column(board_id, column_id, **body.model_dump(exclude_none=True))
    if not col:
        raise HTTPException(404, "Column not found")
    _sync_board_if_enabled(board_id)
    return col


@app.delete("/api/boards/{board_id}/columns/{column_id}")
def api_delete_column(board_id: str, column_id: str):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    if not bs.delete_column(board_id, column_id):
        raise HTTPException(404, "Column not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


# --- Cards ---

@app.get("/api/boards/{board_id}/cards")
def api_list_cards(board_id: str, priority: str | None = None, label: str | None = None, column_id: str | None = None, parent_id: str | None = None):
    _board_or_404(board_id)
    return cs.list_cards(board_id, priority=priority, label=label, column_id=column_id, parent_id=parent_id)


@app.get("/api/boards/{board_id}/cards/search")
def api_search_cards(board_id: str, query: str = "", priority: str | None = None, label: str | None = None):
    board = _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id)]
    columns = [column.model_dump(mode="json") for column in board.columns]
    edges = [edge.model_dump(mode="json") for edge in es.list_edges(board_id)]
    try:
        return search_logic.search_cards(cards, columns, query=query, priority=priority, label=label, edges=edges)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/cards", status_code=201)
def api_create_card(board_id: str, body: CreateCard):
    _board_or_404(board_id)
    card = cs.create_card(board_id, body)
    if not card:
        raise HTTPException(400, "Invalid column_id or board")
    _sync_board_if_enabled(board_id)
    return card


@app.get("/api/boards/{board_id}/cards/{card_id}")
def api_get_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.get_card(board_id, card_id)
    if not card:
        raise HTTPException(404, "Card not found")
    return card


@app.patch("/api/boards/{board_id}/cards/{card_id}")
def api_update_card(board_id: str, card_id: str, body: UpdateCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.update_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/move")
def api_move_card(board_id: str, card_id: str, body: MoveCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.move_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card or target column not found")
    _sync_board_if_enabled(board_id)
    return card


@app.delete("/api/boards/{board_id}/cards/{card_id}")
def api_delete_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if not cs.delete_card(board_id, card_id):
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


@app.post("/api/boards/{board_id}/cards/{card_id}/sessions", status_code=201)
def api_add_session(board_id: str, card_id: str, body: AddSession):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.add_session(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return card


# --- Edges (arbitrary typed connections between two cards) ---

@app.get("/api/boards/{board_id}/edges")
def api_list_edges(board_id: str, card_id: str | None = None, type: str | None = None):
    _board_or_404(board_id)
    return es.list_edges(board_id, card_id=card_id, type=type)


@app.post("/api/boards/{board_id}/edges", status_code=201)
def api_create_edge(board_id: str, body: CreateEdge):
    _board_or_404(board_id)
    edge = es.create_edge(board_id, body)
    if not edge:
        raise HTTPException(400, "Invalid board or card id")
    _sync_board_if_enabled(board_id)
    return edge


@app.delete("/api/boards/{board_id}/edges/{edge_id}")
def api_delete_edge(board_id: str, edge_id: str):
    _board_or_404(board_id)
    _validate_id(edge_id, "edge_id")
    if not es.delete_edge(board_id, edge_id):
        raise HTTPException(404, "Edge not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


# --- Events ---

@app.get("/api/boards/{board_id}/events")
def api_get_events(board_id: str, limit: int = 100):
    _board_or_404(board_id)
    return cs.get_events(board_id, limit)
