import re

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

import board_store as bs
import card_store as cs
from models import (
    AddSession,
    CreateBoard,
    CreateCard,
    CreateColumn,
    MoveCard,
    UpdateBoard,
    UpdateCard,
    UpdateColumn,
)

# IDs are 12-char hex strings generated by _uid()
_ID_RE = re.compile(r"^[0-9a-f]{12}$")

app = FastAPI(title="Agent Board")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:5174",
        "http://localhost:5175",
        "http://localhost:5176",
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)


def _validate_id(value: str, name: str = "id") -> str:
    if not _ID_RE.match(value):
        raise HTTPException(400, f"Invalid {name}")
    return value


def _board_or_404(board_id: str):
    _validate_id(board_id, "board_id")
    board = bs.get_board(board_id)
    if not board:
        raise HTTPException(404, "Board not found")
    return board


# --- Boards ---

@app.get("/api/boards")
def api_list_boards():
    return bs.list_boards()


@app.post("/api/boards", status_code=201)
def api_create_board(body: CreateBoard):
    return bs.create_board(body.name, body.description, body.columns)


@app.get("/api/boards/{board_id}")
def api_get_board(board_id: str):
    return _board_or_404(board_id)


@app.patch("/api/boards/{board_id}")
def api_update_board(board_id: str, body: UpdateBoard):
    board = bs.update_board(board_id, **body.model_dump(exclude_none=True))
    if not board:
        raise HTTPException(404, "Board not found")
    return board


@app.delete("/api/boards/{board_id}")
def api_delete_board(board_id: str):
    if not bs.delete_board(board_id):
        raise HTTPException(404, "Board not found")
    return {"ok": True}


# --- Columns ---

@app.post("/api/boards/{board_id}/columns", status_code=201)
def api_add_column(board_id: str, body: CreateColumn):
    _board_or_404(board_id)
    col = bs.add_column(board_id, body.name, body.position)
    if not col:
        raise HTTPException(400, "Failed to add column")
    return col


@app.patch("/api/boards/{board_id}/columns/{column_id}")
def api_update_column(board_id: str, column_id: str, body: UpdateColumn):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    col = bs.update_column(board_id, column_id, **body.model_dump(exclude_none=True))
    if not col:
        raise HTTPException(404, "Column not found")
    return col


@app.delete("/api/boards/{board_id}/columns/{column_id}")
def api_delete_column(board_id: str, column_id: str):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    if not bs.delete_column(board_id, column_id):
        raise HTTPException(404, "Column not found")
    return {"ok": True}


# --- Cards ---

@app.get("/api/boards/{board_id}/cards")
def api_list_cards(board_id: str, priority: str | None = None, label: str | None = None, column_id: str | None = None):
    _board_or_404(board_id)
    return cs.list_cards(board_id, priority=priority, label=label, column_id=column_id)


@app.post("/api/boards/{board_id}/cards", status_code=201)
def api_create_card(board_id: str, body: CreateCard):
    _board_or_404(board_id)
    card = cs.create_card(board_id, body)
    if not card:
        raise HTTPException(400, "Invalid column_id or board")
    return card


@app.get("/api/boards/{board_id}/cards/{card_id}")
def api_get_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.get_card(board_id, card_id)
    if not card:
        raise HTTPException(404, "Card not found")
    return card


@app.patch("/api/boards/{board_id}/cards/{card_id}")
def api_update_card(board_id: str, card_id: str, body: UpdateCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.update_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/move")
def api_move_card(board_id: str, card_id: str, body: MoveCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.move_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card or target column not found")
    return card


@app.delete("/api/boards/{board_id}/cards/{card_id}")
def api_delete_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if not cs.delete_card(board_id, card_id):
        raise HTTPException(404, "Card not found")
    return {"ok": True}


@app.post("/api/boards/{board_id}/cards/{card_id}/sessions", status_code=201)
def api_add_session(board_id: str, card_id: str, body: AddSession):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.add_session(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    return card


# --- Events ---

@app.get("/api/boards/{board_id}/events")
def api_get_events(board_id: str, limit: int = 100):
    _board_or_404(board_id)
    return cs.get_events(board_id, limit)
