import re
from datetime import datetime

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

import board_store as bs
import canvas_sync
import card_bulk
import card_history
import card_store as cs
import edge_store as es
import search_logic
from models import (
    AddNote,
    AddSession,
    AnswerNote,
    BulkCards,
    CreateBoard,
    CreateCard,
    CreateColumn,
    CreateEdge,
    EnsureProjectBoard,
    LinkProjectRemote,
    MoveCard,
    RevertCard,
    UpdateBoard,
    UpdateCard,
    UpdateColumn,
)

# IDs are 12-char hex strings generated by _uid()
_ID_RE = re.compile(r"^[0-9a-f]{12}$")

app = FastAPI(title="Agent Board")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:5174",
        "http://localhost:5175",
        "http://localhost:5176",
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Attribution only: this server is shared, so the calling session travels in a
# header and is bound to the request's context for the store to read. It is
# caller-asserted and grants nothing — never treat it as authentication.
_SESSION_HEADER = "X-Better-Agent-Session"
_MAX_SESSION_ID = 200


@app.middleware("http")
async def _bind_calling_session(request, call_next):
    raw = (request.headers.get(_SESSION_HEADER) or "").strip()
    token = cs.request_session.set(raw[:_MAX_SESSION_ID] if raw.isprintable() else "")
    try:
        return await call_next(request)
    finally:
        cs.request_session.reset(token)


def _validate_id(value: str, name: str = "id") -> str:
    if not _ID_RE.match(value):
        raise HTTPException(400, f"Invalid {name}")
    return value


def _board_or_404(board_id: str):
    _validate_id(board_id, "board_id")
    board = bs.get_board(board_id)
    if not board:
        raise HTTPException(404, "Board not found")
    return board


def _sync_board_if_enabled(board_id: str) -> None:
    canvas_sync.sync_if_enabled(board_id)


class ImportCard(BaseModel):
    external_id: str = ""
    title: str
    body: str = ""
    column: str
    parent_external_id: str | None = None
    priority: str = "medium"
    labels: list[str] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)


class ImportBoard(BaseModel):
    name: str
    description: str = ""
    columns: list[str]
    cards: list[ImportCard] = Field(default_factory=list)


class CanvasSyncEnable(BaseModel):
    canvas_api_url: str | None = None


# --- Boards ---

@app.get("/api/boards")
def api_list_boards():
    return bs.list_boards()


@app.post("/api/boards", status_code=201)
def api_create_board(body: CreateBoard):
    return bs.create_board(body.name, body.description, body.columns)


@app.get("/api/boards/{board_id}")
def api_get_board(board_id: str):
    return _board_or_404(board_id)


@app.patch("/api/boards/{board_id}")
def api_update_board(board_id: str, body: UpdateBoard):
    try:
        board = bs.update_board(board_id, **body.model_dump(exclude_none=True))
    except bs.ProjectRemoteConflictError as exc:
        raise HTTPException(409, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if not board:
        raise HTTPException(404, "Board not found")
    _sync_board_if_enabled(board_id)
    return board


@app.delete("/api/boards/{board_id}")
def api_delete_board(board_id: str):
    _board_or_404(board_id)
    canvas_sync.disable_sync(board_id)
    if not bs.delete_board(board_id):
        raise HTTPException(404, "Board not found")
    return {"ok": True}


@app.post("/api/projects/ensure-board")
def api_ensure_project_board(body: EnsureProjectBoard):
    try:
        return bs.ensure_project_board(body.remote_url, body.name, body.description, body.columns)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/project-remotes")
def api_link_project_remote(board_id: str, body: LinkProjectRemote):
    _validate_id(board_id, "board_id")
    try:
        board = bs.link_project_remote(board_id, body.remote_url)
    except bs.ProjectRemoteConflictError as exc:
        raise HTTPException(409, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if not board:
        raise HTTPException(404, "Board not found")
    return board


@app.post("/api/import/board", status_code=201)
def api_import_board(body: ImportBoard):
    if not body.columns:
        raise HTTPException(400, "columns must not be empty")
    board = bs.create_board(body.name, body.description, body.columns)
    columns = {col.name: col.id for col in board.columns}
    created_by_external_id: dict[str, str] = {}
    pending = list(body.cards)
    while pending:
        remaining: list[ImportCard] = []
        created_any = False
        for card in pending:
            column_id = columns.get(card.column)
            if not column_id:
                raise HTTPException(400, f"unknown column: {card.column}")
            parent_id = None
            if card.parent_external_id:
                parent_id = created_by_external_id.get(card.parent_external_id)
                if not parent_id:
                    remaining.append(card)
                    continue
            created = cs.create_card(board.id, CreateCard(
                external_id=card.external_id,
                title=card.title,
                body=card.body,
                column_id=column_id,
                parent_id=parent_id,
                priority=card.priority,
                labels=card.labels,
                metadata=card.metadata,
            ))
            if not created:
                raise HTTPException(400, f"failed to create card: {card.title}")
            if card.external_id:
                created_by_external_id[card.external_id] = created.id
            created_any = True
        if remaining and not created_any:
            missing = sorted({c.parent_external_id for c in remaining if c.parent_external_id})
            raise HTTPException(400, f"unknown parent_external_id values: {missing}")
        pending = remaining
    return board


@app.get("/api/boards/{board_id}/canvas-sync")
def api_get_canvas_sync(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.get_sync_status(board_id)


@app.post("/api/boards/{board_id}/canvas-sync/enable")
def api_enable_canvas_sync(board_id: str, body: CanvasSyncEnable | None = None):
    _board_or_404(board_id)
    try:
        return canvas_sync.enable_sync(board_id, body.canvas_api_url if body else None)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/canvas-sync/disable")
def api_disable_canvas_sync(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.disable_sync(board_id)


@app.post("/api/boards/{board_id}/canvas-sync/sync")
def api_sync_canvas(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.sync_board(board_id)


# --- Columns ---

@app.post("/api/boards/{board_id}/columns", status_code=201)
def api_add_column(board_id: str, body: CreateColumn):
    _board_or_404(board_id)
    col = bs.add_column(board_id, body.name, body.position)
    if not col:
        raise HTTPException(400, "Failed to add column")
    _sync_board_if_enabled(board_id)
    return col


@app.patch("/api/boards/{board_id}/columns/{column_id}")
def api_update_column(board_id: str, column_id: str, body: UpdateColumn):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    col = bs.update_column(board_id, column_id, **body.model_dump(exclude_none=True))
    if not col:
        raise HTTPException(404, "Column not found")
    _sync_board_if_enabled(board_id)
    return col


@app.delete("/api/boards/{board_id}/columns/{column_id}")
def api_delete_column(board_id: str, column_id: str):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    if not bs.delete_column(board_id, column_id):
        raise HTTPException(404, "Column not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


# --- Cards ---

@app.get("/api/boards/{board_id}/cards")
def api_list_cards(
    board_id: str,
    priority: str | None = None,
    label: str | None = None,
    column_id: str | None = None,
    parent_id: str | None = None,
    sort: str = "board",
):
    _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id, priority=priority, label=label, column_id=column_id, parent_id=parent_id)]
    return search_logic.sort_cards(cards, sort)


@app.get("/api/boards/{board_id}/cards/search")
def api_search_cards(board_id: str, query: str = "", priority: str | None = None, label: str | None = None, sort: str = "board"):
    board = _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id)]
    columns = [column.model_dump(mode="json") for column in board.columns]
    edges = [edge.model_dump(mode="json") for edge in es.list_edges(board_id)]
    try:
        return search_logic.search_cards(cards, columns, query=query, priority=priority, label=label, edges=edges, sort=sort)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.get("/api/boards/{board_id}/cards/ai-search")
def api_ai_search_cards(
    board_id: str,
    query: str = "",
    priority: str | None = None,
    label: str | None = None,
    max_results: int = Query(12, ge=1, le=50),
):
    board = _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id)]
    columns = [column.model_dump(mode="json") for column in board.columns]
    edges = [edge.model_dump(mode="json") for edge in es.list_edges(board_id)]
    try:
        return search_logic.ai_search_cards(
            cards,
            columns,
            query=query,
            priority=priority,
            label=label,
            edges=edges,
            max_results=max_results,
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/cards", status_code=201)
def api_create_card(board_id: str, body: CreateCard):
    _board_or_404(board_id)
    card = cs.create_card(board_id, body)
    if not card:
        raise HTTPException(400, "Invalid column_id or board")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/bulk")
def api_bulk_cards(board_id: str, body: BulkCards):
    """Apply an ordered batch of card operations atomically."""
    _board_or_404(board_id)
    result = card_bulk.bulk_cards(board_id, body)
    if not result.applied:
        raise HTTPException(422, result.model_dump())
    _sync_board_if_enabled(board_id)
    return result


@app.get("/api/boards/{board_id}/cards/{card_id}")
def api_get_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.get_card(board_id, card_id)
    if not card:
        raise HTTPException(404, "Card not found")
    return card


@app.patch("/api/boards/{board_id}/cards/{card_id}")
def api_update_card(board_id: str, card_id: str, body: UpdateCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.update_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/move")
def api_move_card(board_id: str, card_id: str, body: MoveCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.move_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card or target column not found")
    _sync_board_if_enabled(board_id)
    return card


@app.delete("/api/boards/{board_id}/cards/{card_id}")
def api_delete_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if not cs.delete_card(board_id, card_id):
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


@app.post("/api/boards/{board_id}/cards/{card_id}/sessions", status_code=201)
def api_add_session(board_id: str, card_id: str, body: AddSession):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.add_session(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/notes", status_code=201)
def api_add_note(board_id: str, card_id: str, body: AddNote):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.add_note(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found or note text empty")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/notes/{note_id}/answer")
def api_answer_note(board_id: str, card_id: str, note_id: str, body: AnswerNote):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    _validate_id(note_id, "note_id")
    card = cs.answer_note(board_id, card_id, note_id, body)
    if not card:
        raise HTTPException(404, "Question not found or answer empty")
    _sync_board_if_enabled(board_id)
    return card


@app.get("/api/questions/open")
def api_open_questions(board_id: str | None = None):
    """Unanswered questions across every board, for attention surfaces."""
    if board_id:
        _board_or_404(board_id)
    items = cs.open_questions(board_id)
    return {"count": len(items), "questions": items}


# --- Card history (the journal, not the card's capped projection) ---

@app.get("/api/boards/{board_id}/cards/{card_id}/history")
def api_card_history(board_id: str, card_id: str, at: datetime | None = None):
    """Every recorded version of a card. With ``at``, the single version the
    card stood at that moment instead. Answers for deleted cards too, because
    the journal outlives them."""
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if at is not None:
        version = card_history.card_as_of(board_id, card_id, at)
        if not version:
            raise HTTPException(404, "Card did not exist at that time")
        return version
    versions = card_history.card_versions(board_id, card_id)
    if not versions:
        raise HTTPException(404, "No history for that card")
    return {"card_id": card_id, "count": len(versions), "versions": versions}


@app.post("/api/boards/{board_id}/cards/{card_id}/revert")
def api_revert_card(board_id: str, card_id: str, body: RevertCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.revert_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card, version, or its original column no longer exists")
    _sync_board_if_enabled(board_id)
    return card


@app.get("/api/sessions/{session_id}/activity")
def api_session_activity(
    session_id: str,
    board_id: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
):
    """What one session did, across boards."""
    if board_id:
        _board_or_404(board_id)
    events = card_history.session_activity(session_id, board_id, limit)
    return {"session_id": session_id, "count": len(events), "events": events}


# --- Edges (arbitrary typed connections between two cards) ---

@app.get("/api/boards/{board_id}/edges")
def api_list_edges(board_id: str, card_id: str | None = None, type: str | None = None):
    _board_or_404(board_id)
    return es.list_edges(board_id, card_id=card_id, type=type)


@app.post("/api/boards/{board_id}/edges", status_code=201)
def api_create_edge(board_id: str, body: CreateEdge):
    _board_or_404(board_id)
    edge = es.create_edge(board_id, body)
    if not edge:
        raise HTTPException(400, "Invalid board or card id")
    _sync_board_if_enabled(board_id)
    return edge


@app.delete("/api/boards/{board_id}/edges/{edge_id}")
def api_delete_edge(board_id: str, edge_id: str):
    _board_or_404(board_id)
    _validate_id(edge_id, "edge_id")
    if not es.delete_edge(board_id, edge_id):
        raise HTTPException(404, "Edge not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


# --- Events ---

@app.get("/api/boards/{board_id}/events")
def api_get_events(board_id: str, limit: int = 100):
    _board_or_404(board_id)
    return cs.get_events(board_id, limit)
