"""Unit tests for the stale `agent-board` wrapper detector in install.py."""

from __future__ import annotations

import os
from pathlib import Path

from agent_board import install

STALE_WRAPPER = (
    "#!/bin/bash\n"
    "# agent-board CLI wrapper (generated by install.py).\n"
    'exec "/home/u/agent-board/backend/.venv/bin/python" '
    '"/home/u/agent-board/backend/cli.py" "$@"\n'
)

CONSOLE_SCRIPT = (
    "#!/usr/bin/python3\n"
    "import sys\n"
    "from agent_board.cli import main\n"
    "sys.exit(main())\n"
)


def _install_fake(tmp_path: Path, monkeypatch, body: str) -> Path:
    target = tmp_path / "agent-board"
    target.write_text(body)
    target.chmod(0o755)
    monkeypatch.setenv("PATH", str(tmp_path) + os.pathsep + os.environ.get("PATH", ""))
    return target


def test_warns_on_stale_wrapper(tmp_path, monkeypatch, capsys):
    found = _install_fake(tmp_path, monkeypatch, STALE_WRAPPER)
    install._warn_stale_cli_wrapper()
    out = capsys.readouterr().out
    assert "stale wrapper" in out
    assert str(found) in out


def test_silent_on_console_script(tmp_path, monkeypatch, capsys):
    _install_fake(tmp_path, monkeypatch, CONSOLE_SCRIPT)
    install._warn_stale_cli_wrapper()
    assert capsys.readouterr().out == ""


def test_silent_when_command_absent(tmp_path, monkeypatch, capsys):
    monkeypatch.setenv("PATH", str(tmp_path))  # empty dir, no agent-board
    install._warn_stale_cli_wrapper()
    assert capsys.readouterr().out == ""
