import asyncio
import fcntl
import re
import sys
from contextlib import suppress
from datetime import datetime
from pathlib import Path
from typing import Literal

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from . import board_consolidation
from . import board_store as bs
from . import canvas_sync
from . import card_bulk
from . import card_history
from . import card_projection
from . import card_store as cs
from . import db
from . import edge_store as es
from . import search_logic
from . import validation_worker
from . import vote_store
from .git_revision import GitRevisionError, current_commit
from .models import (
    AddNote,
    AddSession,
    AnswerNote,
    BulkCards,
    CHANGE_NATIVE_SESSION_HEADER,
    CHANGE_PROVIDER_HEADER,
    ChangeContext,
    CreateBoard,
    CreateCard,
    CreateColumn,
    CreateEdge,
    ConsolidateProjectBoard,
    EnsureProjectBoard,
    LinkProjectRemote,
    MoveCard,
    RevertCard,
    UpdateBoard,
    UpdateCard,
    UpdateColumn,
)
from .card_semantics import CardSemantics

# IDs are 12-char hex strings generated by new_id().
_ID_RE = re.compile(r"^[0-9a-f]{12}$")
_CHANGE_ID_RE = re.compile(r"^[0-9a-f]{64}$")

app = FastAPI(title="Agent Board")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://localhost:5174",
        "http://localhost:5175",
        "http://localhost:5176",
    ],
    allow_methods=["*"],
    allow_headers=["*"],
)

_validation_task: asyncio.Task | None = None


@app.on_event("startup")
async def _start_validation_worker():
    """Deterministic card checks run in the background for as long as the server
    does. Off by env var for anyone who wants a quiet board."""
    global _validation_task
    db.initialize_storage()
    try:
        board_consolidation.recover_pending_consolidations()
    except Exception as exc:
        sys.stderr.write(
            f"Board consolidation recovery failed: {type(exc).__name__}\n"
        )
    if validation_worker.is_enabled():
        _validation_task = asyncio.create_task(validation_worker.run_forever())


@app.on_event("shutdown")
async def _stop_validation_worker():
    global _validation_task
    if _validation_task:
        _validation_task.cancel()
        with suppress(asyncio.CancelledError):
            await _validation_task
        _validation_task = None


_CARD_MUTATION_RE = re.compile(
    r"^/api/boards/[0-9a-f]{12}/cards(?:$|/bulk$|/[0-9a-f]{12}"
    r"(?:$|/move$|/sessions$|/notes(?:$|/[0-9a-f]{12}/answer$)|/revert$"
    r"|/changes/[0-9a-f]{64}/vote$))"
)


def _requires_change_context(method: str, path: str) -> bool:
    return method in {"POST", "PATCH", "DELETE"} and bool(
        _CARD_MUTATION_RE.fullmatch(path)
    )


@app.middleware("http")
async def _guard_consolidations(request, call_next):
    is_consolidation = request.url.path == "/api/projects/consolidate-board"
    lock_file = open(board_consolidation.api_lock_path(), "w")
    operation = fcntl.LOCK_EX if is_consolidation else fcntl.LOCK_SH
    await asyncio.to_thread(fcntl.flock, lock_file, operation)
    try:
        if board_consolidation.has_pending_consolidation() and not is_consolidation:
            return JSONResponse(
                status_code=503,
                content={"detail": "Board consolidation recovery is pending"},
            )
        return await call_next(request)
    finally:
        await asyncio.to_thread(fcntl.flock, lock_file, fcntl.LOCK_UN)
        lock_file.close()


@app.middleware("http")
async def _bind_change_context(request, call_next):
    context = None
    if _requires_change_context(request.method, request.url.path):
        try:
            context = ChangeContext.from_headers(request.headers)
        except ValueError as exc:
            return JSONResponse(status_code=400, content={"detail": str(exc)})
    token = cs.request_change_context.set(context)
    try:
        return await call_next(request)
    finally:
        cs.request_change_context.reset(token)


def _validate_id(value: str, name: str = "id") -> str:
    if not _ID_RE.match(value):
        raise HTTPException(400, f"Invalid {name}")
    return value


def _board_or_404(board_id: str):
    _validate_id(board_id, "board_id")
    board = bs.get_board(board_id)
    if not board:
        raise HTTPException(404, "Board not found")
    return board


def _sync_board_if_enabled(board_id: str) -> None:
    canvas_sync.sync_if_enabled(board_id)


def _repository_head() -> str:
    try:
        return current_commit(str(Path(__file__).resolve().parent.parent))
    except GitRevisionError as exc:
        raise HTTPException(503, str(exc)) from exc


class ImportCard(BaseModel):
    external_id: str = ""
    title: str
    body: str = ""
    column: str
    parent_external_id: str | None = None
    priority: str = "medium"
    labels: list[str] = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)
    semantics: CardSemantics = Field(default_factory=CardSemantics)


class ImportBoard(BaseModel):
    name: str
    description: str = ""
    columns: list[str]
    cards: list[ImportCard] = Field(default_factory=list)


class CanvasSyncEnable(BaseModel):
    canvas_api_url: str | None = None


class SetChangeVote(BaseModel):
    direction: Literal[-1, 1]


# --- Boards ---

@app.get("/api/revision")
def api_revision():
    return {"commit_sha": _repository_head()}

@app.get("/api/boards")
def api_list_boards():
    return bs.list_boards()


@app.post("/api/boards", status_code=201)
def api_create_board(body: CreateBoard):
    return bs.create_board(body.name, body.description, body.columns)


@app.get("/api/boards/{board_id}")
def api_get_board(board_id: str):
    return _board_or_404(board_id)


@app.patch("/api/boards/{board_id}")
def api_update_board(board_id: str, body: UpdateBoard):
    try:
        board = bs.update_board(board_id, **body.model_dump(exclude_none=True))
    except bs.ProjectRemoteConflictError as exc:
        raise HTTPException(409, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if not board:
        raise HTTPException(404, "Board not found")
    _sync_board_if_enabled(board_id)
    return board


@app.delete("/api/boards/{board_id}")
def api_delete_board(board_id: str):
    _board_or_404(board_id)
    canvas_sync.disable_sync(board_id)
    if not bs.delete_board(board_id):
        raise HTTPException(404, "Board not found")
    return {"ok": True}


@app.post("/api/projects/ensure-board")
def api_ensure_project_board(body: EnsureProjectBoard):
    try:
        return bs.ensure_project_board(body.remote_url, body.name, body.description, body.columns)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/project-remotes")
def api_link_project_remote(board_id: str, body: LinkProjectRemote):
    _validate_id(board_id, "board_id")
    try:
        board = bs.link_project_remote(board_id, body.remote_url)
    except bs.ProjectRemoteConflictError as exc:
        raise HTTPException(409, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    if not board:
        raise HTTPException(404, "Board not found")
    return board


@app.post("/api/projects/consolidate-board")
def api_consolidate_project_board(body: ConsolidateProjectBoard):
    try:
        return board_consolidation.consolidate_project_board(
            body.source_board_id,
            body.target_board_id,
        )
    except KeyError as exc:
        raise HTTPException(404, str(exc)) from exc
    except board_consolidation.ConsolidationConflictError as exc:
        raise HTTPException(409, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/import/board", status_code=201)
def api_import_board(body: ImportBoard):
    if not body.columns:
        raise HTTPException(400, "columns must not be empty")
    board = bs.create_board(body.name, body.description, body.columns)
    columns = {col.name: col.id for col in board.columns}
    created_by_external_id: dict[str, str] = {}
    pending = list(body.cards)
    while pending:
        remaining: list[ImportCard] = []
        created_any = False
        for card in pending:
            column_id = columns.get(card.column)
            if not column_id:
                raise HTTPException(400, f"unknown column: {card.column}")
            parent_id = None
            if card.parent_external_id:
                parent_id = created_by_external_id.get(card.parent_external_id)
                if not parent_id:
                    remaining.append(card)
                    continue
            created = cs.create_card(board.id, CreateCard(
                external_id=card.external_id,
                title=card.title,
                body=card.body,
                column_id=column_id,
                parent_id=parent_id,
                priority=card.priority,
                labels=card.labels,
                metadata=card.metadata,
                semantics=card.semantics,
            ))
            if not created:
                raise HTTPException(400, f"failed to create card: {card.title}")
            if card.external_id:
                created_by_external_id[card.external_id] = created.id
            created_any = True
        if remaining and not created_any:
            missing = sorted({c.parent_external_id for c in remaining if c.parent_external_id})
            raise HTTPException(400, f"unknown parent_external_id values: {missing}")
        pending = remaining
    return board


@app.get("/api/boards/{board_id}/canvas-sync")
def api_get_canvas_sync(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.get_sync_status(board_id)


@app.post("/api/boards/{board_id}/canvas-sync/enable")
def api_enable_canvas_sync(board_id: str, body: CanvasSyncEnable | None = None):
    _board_or_404(board_id)
    try:
        return canvas_sync.enable_sync(board_id, body.canvas_api_url if body else None)
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/canvas-sync/disable")
def api_disable_canvas_sync(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.disable_sync(board_id)


@app.post("/api/boards/{board_id}/canvas-sync/sync")
def api_sync_canvas(board_id: str):
    _board_or_404(board_id)
    return canvas_sync.sync_board(board_id)


# --- Columns ---

@app.post("/api/boards/{board_id}/columns", status_code=201)
def api_add_column(board_id: str, body: CreateColumn):
    _board_or_404(board_id)
    col = bs.add_column(board_id, body.name, body.position)
    if not col:
        raise HTTPException(400, "Failed to add column")
    _sync_board_if_enabled(board_id)
    return col


@app.patch("/api/boards/{board_id}/columns/{column_id}")
def api_update_column(board_id: str, column_id: str, body: UpdateColumn):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    col = bs.update_column(board_id, column_id, **body.model_dump(exclude_none=True))
    if not col:
        raise HTTPException(404, "Column not found")
    _sync_board_if_enabled(board_id)
    return col


@app.delete("/api/boards/{board_id}/columns/{column_id}")
def api_delete_column(board_id: str, column_id: str):
    _board_or_404(board_id)
    _validate_id(column_id, "column_id")
    if not bs.delete_column(board_id, column_id):
        raise HTTPException(404, "Column not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


# --- Cards ---

@app.get("/api/boards/{board_id}/cards")
def api_list_cards(
    board_id: str,
    priority: str | None = None,
    label: str | None = None,
    column_id: str | None = None,
    parent_id: str | None = None,
    sort: str = "board",
    limit: int = Query(card_projection.DEFAULT_PAGE_LIMIT, ge=1, le=card_projection.MAX_PAGE_LIMIT),
    cursor: str | None = None,
    include: list[str] | None = Query(None, description=card_projection.INCLUDE_FIELDS_DESCRIPTION),
    exclude: list[str] | None = Query(None, description=card_projection.EXCLUDE_FIELDS_DESCRIPTION),
):
    """List cards. The default projection contains every card and derived field."""
    _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id, priority=priority, label=label, column_id=column_id, parent_id=parent_id)]
    coverage = card_projection.coverage_extras(
        cards,
        [edge.model_dump(mode="json") for edge in es.list_edges(board_id)],
    )
    ordered = search_logic.sort_cards(cards, sort, tie_breaker=True)
    try:
        selected_fields = card_projection.resolve_card_fields(
            "list_cards", include=include, exclude=exclude
        )
        return card_projection.page_cards(
            ordered,
            board_id=board_id,
            endpoint="list_cards",
            request={
                "priority": priority,
                "label": label,
                "column_id": column_id,
                "parent_id": parent_id,
                "sort": sort,
            },
            limit=limit,
            cursor=cursor,
            sort_key=lambda card: search_logic.card_sort_key(card, sort),
            item_extras=coverage,
            selected_fields=selected_fields,
        )
    except card_projection.InvalidCursor as exc:
        raise HTTPException(400, str(exc)) from exc
    except card_projection.StaleCursor as exc:
        raise HTTPException(400, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.get("/api/boards/{board_id}/cards/search")
def api_search_cards(
    board_id: str,
    query: str = "",
    priority: str | None = None,
    label: str | None = None,
    sort: str = "board",
    limit: int = Query(card_projection.DEFAULT_PAGE_LIMIT, ge=1, le=card_projection.MAX_PAGE_LIMIT),
    cursor: str | None = None,
    include: list[str] | None = Query(None, description=card_projection.INCLUDE_FIELDS_DESCRIPTION),
    exclude: list[str] | None = Query(None, description=card_projection.EXCLUDE_FIELDS_DESCRIPTION),
):
    """Search cards with every card field, derived field, and relation_roles by default."""
    board = _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id)]
    columns = [column.model_dump(mode="json") for column in board.columns]
    edges = [edge.model_dump(mode="json") for edge in es.list_edges(board_id)]
    coverage = card_projection.coverage_extras(cards, edges)
    try:
        ordered, relation_roles = search_logic.search_cards_with_roles(
            cards, columns, query=query, priority=priority, label=label, edges=edges, sort=sort
        )
        ordered = search_logic.sort_cards(ordered, sort, tie_breaker=True)
        selected_fields = card_projection.resolve_card_fields(
            "search_cards", include=include, exclude=exclude
        )
        return card_projection.page_cards(
            ordered,
            board_id=board_id,
            endpoint="search_cards",
            request={
                "query": query,
                "priority": priority,
                "label": label,
                "sort": sort,
            },
            limit=limit,
            cursor=cursor,
            sort_key=lambda card: search_logic.card_sort_key(card, sort),
            relation_roles=relation_roles,
            item_extras=coverage,
            selected_fields=selected_fields,
        )
    except card_projection.InvalidCursor as exc:
        raise HTTPException(400, str(exc)) from exc
    except card_projection.StaleCursor as exc:
        raise HTTPException(400, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.get("/api/boards/{board_id}/cards/relevant-candidates")
def api_relevant_candidates(
    board_id: str,
    query: str = "",
    priority: str | None = None,
    label: str | None = None,
    max_candidates: int = Query(search_logic._SHORTLIST_CAP, ge=1, le=50),
    limit: int = Query(card_projection.DEFAULT_PAGE_LIMIT, ge=1, le=card_projection.MAX_PAGE_LIMIT),
    cursor: str | None = None,
    include: list[str] | None = Query(None, description=card_projection.INCLUDE_FIELDS_DESCRIPTION),
    exclude: list[str] | None = Query(None, description=card_projection.EXCLUDE_FIELDS_DESCRIPTION),
):
    """Keyword-relevance shortlist only -- a building block for semantic/AI
    ranking, not itself a semantic ranker (agent-board has no AI provider).
    Callers who want AI ranking send this candidate list to a model themselves.
    The default projection includes every card field, derived field,
    relevance_score, and column."""
    board = _board_or_404(board_id)
    cards = [card.model_dump(mode="json") for card in cs.list_cards(board_id)]
    columns = [column.model_dump(mode="json") for column in board.columns]
    edges = [edge.model_dump(mode="json") for edge in es.list_edges(board_id)]
    coverage = card_projection.coverage_extras(cards, edges)
    try:
        ranked, scores, column_names, error = search_logic.ranked_relevant_cards(
            cards,
            columns,
            query=query,
            priority=priority,
            label=label,
            edges=edges,
            max_candidates=max_candidates,
        )
        extras = {
            card["id"]: {
                "relevance_score": scores[card["id"]],
                "column": column_names.get(card.get("column_id"), card.get("column_id", "")),
                **coverage.get(card["id"], {}),
            }
            for card in ranked
        }
        selected_fields = card_projection.resolve_card_fields(
            "relevant_candidates", include=include, exclude=exclude
        )
        return card_projection.page_cards(
            ranked,
            board_id=board_id,
            endpoint="relevant_candidates",
            request={
                "query": query,
                "priority": priority,
                "label": label,
                "max_candidates": max_candidates,
            },
            limit=limit,
            cursor=cursor,
            sort_key=lambda card: (
                -scores[card["id"]],
                *search_logic.card_sort_key(card, "board"),
            ),
            item_extras=extras,
            envelope_extras={"error": error},
            selected_fields=selected_fields,
        )
    except card_projection.InvalidCursor as exc:
        raise HTTPException(400, str(exc)) from exc
    except card_projection.StaleCursor as exc:
        raise HTTPException(400, str(exc)) from exc
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc


@app.post("/api/boards/{board_id}/cards", status_code=201)
def api_create_card(board_id: str, body: CreateCard):
    _board_or_404(board_id)
    card = cs.create_card(board_id, body)
    if not card:
        raise HTTPException(400, "Invalid column_id or board")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/bulk")
def api_bulk_cards(board_id: str, body: BulkCards):
    """Apply an ordered batch of card operations atomically."""
    _board_or_404(board_id)
    result = card_bulk.bulk_cards(board_id, body)
    if not result.applied:
        raise HTTPException(422, result.model_dump())
    _sync_board_if_enabled(board_id)
    return result


@app.get("/api/boards/{board_id}/cards/{card_id}")
def api_get_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.get_card(board_id, card_id)
    if not card:
        raise HTTPException(404, "Card not found")
    return card


@app.patch("/api/boards/{board_id}/cards/{card_id}")
def api_update_card(board_id: str, card_id: str, body: UpdateCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.update_card(board_id, card_id, body)
    if not card:
        if not cs.get_card(board_id, card_id):
            raise HTTPException(404, "Card not found")
        raise HTTPException(
            409,
            "Update has an unknown column, invalid parent or semantic hierarchy, or edge conflict",
        )
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/move")
def api_move_card(board_id: str, card_id: str, body: MoveCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.move_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card or target column not found")
    _sync_board_if_enabled(board_id)
    return card


@app.delete("/api/boards/{board_id}/cards/{card_id}")
def api_delete_card(board_id: str, card_id: str):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if not cs.delete_card(board_id, card_id):
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


@app.post("/api/boards/{board_id}/cards/{card_id}/sessions", status_code=201)
def api_add_session(board_id: str, card_id: str, body: AddSession):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.add_session(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/notes", status_code=201)
def api_add_note(board_id: str, card_id: str, body: AddNote):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.add_note(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card not found or note text empty")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/cards/{card_id}/notes/{note_id}/answer")
def api_answer_note(board_id: str, card_id: str, note_id: str, body: AnswerNote):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    _validate_id(note_id, "note_id")
    card = cs.answer_note(board_id, card_id, note_id, body)
    if not card:
        raise HTTPException(404, "Question not found or answer empty")
    _sync_board_if_enabled(board_id)
    return card


@app.post("/api/boards/{board_id}/validate")
def api_validate_board(board_id: str):
    """Run the deterministic checks now instead of waiting for the interval."""
    _board_or_404(board_id)
    result = validation_worker.scan_and_apply(board_id)
    _sync_board_if_enabled(board_id)
    return result


@app.get("/api/questions/open")
def api_open_questions(board_id: str | None = None):
    """Unanswered questions across every board, for attention surfaces."""
    if board_id:
        _board_or_404(board_id)
    items = cs.open_questions(board_id)
    return {"count": len(items), "questions": items}


# --- Card history (the journal, not the card's capped projection) ---

@app.get("/api/boards/{board_id}/cards/{card_id}/history")
def api_card_history(board_id: str, card_id: str, at: datetime | None = None):
    """Every recorded version of a card. With ``at``, the single version the
    card stood at that moment instead. Answers for deleted cards too, because
    the journal outlives them."""
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if at is not None:
        version = card_history.card_as_of(board_id, card_id, at)
        if not version:
            raise HTTPException(404, "Card did not exist at that time")
        return version
    versions = card_history.card_versions(board_id, card_id)
    if not versions:
        raise HTTPException(404, "No history for that card")
    return {"card_id": card_id, "count": len(versions), "versions": versions}


@app.post("/api/boards/{board_id}/cards/{card_id}/revert")
def api_revert_card(board_id: str, card_id: str, body: RevertCard):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    card = cs.revert_card(board_id, card_id, body)
    if not card:
        raise HTTPException(404, "Card, version, or its original column no longer exists")
    _sync_board_if_enabled(board_id)
    return card


@app.get("/api/boards/{board_id}/cards/{card_id}/changes")
def api_card_changes(
    board_id: str,
    card_id: str,
    request: Request,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=200, ge=1, le=1000),
):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    provider = request.headers.get(CHANGE_PROVIDER_HEADER, "")
    native_session_id = request.headers.get(CHANGE_NATIVE_SESSION_HEADER, "")
    context = (
        ChangeContext.reader(provider, native_session_id)
        if provider and native_session_id
        else None
    )
    items = card_history.card_change_items(board_id, card_id, context)
    page = items[offset:offset + limit]
    next_offset = offset + len(page) if offset + len(page) < len(items) else None
    return {
        "card_id": card_id,
        "count": len(items),
        "items": page,
        "next_offset": next_offset,
    }


@app.post("/api/boards/{board_id}/cards/{card_id}/changes/{target_id}/vote")
def api_set_change_vote(
    board_id: str,
    card_id: str,
    target_id: str,
    body: SetChangeVote,
):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if not _CHANGE_ID_RE.fullmatch(target_id):
        raise HTTPException(400, "Invalid change item id")
    try:
        vote = vote_store.set_vote(
            board_id,
            card_id,
            target_id,
            body.direction,
            cs.current_change_context(),
        )
    except ValueError as exc:
        raise HTTPException(400, str(exc)) from exc
    summary = vote_store.vote_summaries(
        [target_id], cs.current_change_context()
    )[target_id]
    return {"vote": vote, "summary": summary}


@app.get("/api/boards/{board_id}/cards/{card_id}/changes/{target_id}/votes")
def api_change_vote_audit(
    board_id: str,
    card_id: str,
    target_id: str,
    offset: int = Query(default=0, ge=0),
    limit: int = Query(default=200, ge=1, le=1000),
):
    _board_or_404(board_id)
    _validate_id(card_id, "card_id")
    if not _CHANGE_ID_RE.fullmatch(target_id):
        raise HTTPException(400, "Invalid change item id")
    if not any(
        item.id == target_id
        for item in card_history.card_change_items(board_id, card_id)
    ):
        raise HTTPException(404, "Change item not found")
    total = db.connect().execute(
        "SELECT COUNT(*) FROM change_votes WHERE target_id=?",
        (target_id,),
    ).fetchone()[0]
    votes = vote_store.vote_audit(target_id, offset, limit)
    next_offset = offset + len(votes) if offset + len(votes) < total else None
    return {
        "target_id": target_id,
        "count": total,
        "votes": votes,
        "next_offset": next_offset,
    }


@app.get("/api/sessions/{session_id}/activity")
def api_session_activity(
    session_id: str,
    board_id: str | None = None,
    limit: int = Query(default=200, ge=1, le=1000),
):
    """What one session did, across boards."""
    if board_id:
        _board_or_404(board_id)
    events = card_history.session_activity(session_id, board_id, limit)
    return {"session_id": session_id, "count": len(events), "events": events}


# --- Edges (arbitrary typed connections between two cards) ---

@app.get("/api/boards/{board_id}/edges")
def api_list_edges(board_id: str, card_id: str | None = None, type: str | None = None):
    _board_or_404(board_id)
    return es.list_edges(board_id, card_id=card_id, type=type)


@app.post("/api/boards/{board_id}/edges", status_code=201)
def api_create_edge(board_id: str, body: CreateEdge):
    _board_or_404(board_id)
    try:
        edge = es.create_edge(board_id, body)
    except es.UnknownEndpoint as exc:
        raise HTTPException(404, str(exc))
    except es.DuplicateEdge as exc:
        raise HTTPException(409, str(exc))
    except es.DependencyCycle as exc:
        raise HTTPException(409, str(exc))
    except (
        es.SelfLoop,
        es.MissingSemanticKind,
        es.InvalidDirection,
        es.ParentRelationshipRequired,
    ) as exc:
        raise HTTPException(422, str(exc))
    _sync_board_if_enabled(board_id)
    return edge


@app.delete("/api/boards/{board_id}/edges/{edge_id}")
def api_delete_edge(board_id: str, edge_id: str):
    _board_or_404(board_id)
    _validate_id(edge_id, "edge_id")
    if not es.delete_edge(board_id, edge_id):
        raise HTTPException(404, "Edge not found")
    _sync_board_if_enabled(board_id)
    return {"ok": True}


# --- Events ---

@app.get("/api/boards/{board_id}/events")
def api_get_events(board_id: str, limit: int = 100):
    _board_or_404(board_id)
    return cs.get_events(board_id, limit)
